version: '3'
services:
  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    ports:
      - "80:80"
    user: "${UID}:${GID}"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql